[package]
name = "mnist"
version = "0.1.0"
edition = "2021"

[dependencies]
alea = "0.2.2"
# smolmatrix = "0.1.6"
smolmatrix = { path = "../../smolmatrix" }
smolnn = { version = "0.1.0", path = ".." }
term_size = "0.3.2"
